@startuml

interface InfoInterface {
    + nome: String?
    + codigo: Int?

    + equals(other: Any?): Boolean
    + create(): InfoInterface
}

abstract Pessoa {
    + {abstract} nome: String?
    + {abstract} codigo: Int?
    + {abstract} sobrenome: String?

    + equals(other: Any?): Boolean
    + {abstract} create(): InfoInterface
}

class Aluno {
    + nome: String?
    + codigo: Int?
    + sobrenome: String
    + create(): InfoInterface
}

InfoInterface <|-- Pessoa
Pessoa <|-- Aluno

abstract Objeto {
    + {abstract} nome: String?
    + {abstract} codigo: Int?

    + equals(other: Any?): Boolean
    + {abstract} create(): InfoInterface
}

class Curso {
    + nome: String?
    + codigo: Int?

    + professor_titular: InfoInterface
    + professor_adjunto: InfoInterface
    + qtde_maxima_de_alunos: Int
    + alunos_matriculados: List<InfoInterface>

    + equals(other: Any?): Boolean
    + create(): InfoInterface
}

InfoInterface <|-- Objeto
Objeto <|-- Curso

class Professor {
    + nome: String?
    + codigo: Int?
    + sobrenome: String

    + is_titular: Boolean
    + is_adjunto: Boolean
    + especialidade: String
    + horas_monitoria: Int

    + create(): InfoInterface
}

Pessoa <|-- Professor

class Matricula {
    + aluno: InfoInterface
    + curso: InfoInterface
    + data_matricula: Date
}

InfoInterface *- Matricula

@enduml