@startuml


interface InfoDataClass


interface InfoInterface {
    # info: InfoDataClass

    + equals(other: Any?): Boolean
}

InfoDataClass *-- InfoInterface

class InfoAluno <<data>> {
    + nome: String
    + sobrenome: String
    + codigo: Int
}

InfoDataClass <|-- InfoAluno

class Aluno {
    info: InfoDataClass

    + equals(other: Any?): Boolean
}

InfoInterface <|-- Aluno

class InfoCurso <<data>> {
    + nome: String
    + sobrenome: String
    + codigo: Int
}

InfoDataClass <|-- InfoCurso

class Curso {
    info: InfoDataClass

    + equals(other: Any?): Boolean
}

InfoInterface <|-- Curso


class InfoProfessor <<data>> {
    + nome: String
    + sobrenome: String
    + codigo: Int
}

InfoDataClass <|-- InfoProfessor

class Professor {
    info: InfoDataClass

    + equals(other: Any?): Boolean
}

InfoInterface <|-- Professor

@enduml